#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

case "$DOKKU_DISTRO" in
  ubuntu)
    export DEBIAN_FRONTEND=noninteractive
    [[ -z "$CIRCLECI" ]] && apt-get install -qq -y software-properties-common python-software-properties
    [[ -n "$CIRCLECI" ]] && aptitude install -q -y software-properties-common python-software-properties
    add-apt-repository -y ppa:nginx/stable
    apt-get update -qq > /dev/null
    apt-get install -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" --force-yes -qq -y nginx dnsutils
    ;;
  debian)
    export DEBIAN_FRONTEND=noninteractive
    echo "deb http://nginx.org/packages/debian/ wheezy nginx" > /etc/apt/sources.list.d/nginx.list
    wget -O - http://nginx.org/keys/nginx_signing.key | apt-key add -
    apt-get update
    apt-get install -y nginx dnsutils
    ;;
  opensuse)
    zypper -q in -y nginx bind-utils
    ;;
esac
